"""initial schema

Revision ID: 2bcc5fe944f3
Revises: 
Create Date: 2026-07-08 20:27:17.035614
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2bcc5fe944f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_problems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('pattern_tag', sa.String(length=60), nullable=True),
    sa.Column('difficulty', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('statement', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('examples_json', sa.JSON(), nullable=True),
    sa.Column('constraints_json', sa.JSON(), nullable=True),
    sa.Column('hints_json', sa.JSON(), nullable=True),
    sa.Column('starter_code_json', sa.JSON(), nullable=True),
    sa.Column('test_cases_json', sa.JSON(), nullable=True),
    sa.Column('optimal_solution', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('complexity', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('review_status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('criteria_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_code'), 'badges', ['code'], unique=True)
    op.create_table('championships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('college_id', sa.String(length=36), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=False),
    sa.Column('question_paper_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('podium_json', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_championships_college_id'), 'championships', ['college_id'], unique=False)
    op.create_table('colleges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('license_seats', sa.Integer(), nullable=False),
    sa.Column('seats_used', sa.Integer(), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colleges_slug'), 'colleges', ['slug'], unique=True)
    op.create_table('company_intel_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_slug', sa.String(length=120), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_intel_cache_company_slug'), 'company_intel_cache', ['company_slug'], unique=True)
    op.create_table('domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_slug'), 'domains', ['slug'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('plan_months', sa.Integer(), nullable=False),
    sa.Column('price_inr', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('profile_bar_score', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_college_id'), 'users', ['college_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('college_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_college_id'), 'admin_users', ['college_id'], unique=False)
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('aptitude_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('level', sa.String(length=15), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('questions_json', sa.JSON(), nullable=True),
    sa.Column('answers_json', sa.JSON(), nullable=True),
    sa.Column('time_taken_secs', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aptitude_sessions_user_id'), 'aptitude_sessions', ['user_id'], unique=False)
    op.create_table('arena_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('code', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('ai_review_json', sa.JSON(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['arena_problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arena_submissions_problem_id'), 'arena_submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_arena_submissions_user_id'), 'arena_submissions', ['user_id'], unique=False)
    op.create_table('championship_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('championship_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('time_used_secs', sa.Integer(), nullable=True),
    sa.Column('fullscreen_exits', sa.Integer(), nullable=False),
    sa.Column('attention_score', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('ai_analysis_json', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('championship_id', 'user_id', name='uq_champ_user')
    )
    op.create_index(op.f('ix_championship_attempts_championship_id'), 'championship_attempts', ['championship_id'], unique=False)
    op.create_index(op.f('ix_championship_attempts_user_id'), 'championship_attempts', ['user_id'], unique=False)
    op.create_table('daily_activity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('questions_attempted', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=False),
    sa.Column('topics_completed', sa.Integer(), nullable=False),
    sa.Column('arena_points', sa.Integer(), nullable=False),
    sa.Column('interview_points', sa.Integer(), nullable=False),
    sa.Column('championship_points', sa.Integer(), nullable=False),
    sa.Column('daily_points', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_user_day')
    )
    op.create_index(op.f('ix_daily_activity_activity_date'), 'daily_activity', ['activity_date'], unique=False)
    op.create_index(op.f('ix_daily_activity_user_id'), 'daily_activity', ['user_id'], unique=False)
    op.create_table('domain_phases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('min_plan_months', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_phases_domain_id'), 'domain_phases', ['domain_id'], unique=False)
    op.create_table('interview_studio_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=60), nullable=True),
    sa.Column('level', sa.String(length=15), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('transcript_json', sa.JSON(), nullable=True),
    sa.Column('per_question_scores_json', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('presence_pct', sa.Integer(), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_studio_sessions_user_id'), 'interview_studio_sessions', ['user_id'], unique=False)
    op.create_table('leaderboard',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('college_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=12), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_college_id'), 'leaderboard', ['college_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_user_id'), 'leaderboard', ['user_id'], unique=False)
    op.create_table('mock_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('domain', sa.String(length=60), nullable=True),
    sa.Column('level', sa.String(length=15), nullable=True),
    sa.Column('questions_json', sa.JSON(), nullable=True),
    sa.Column('answers_json', sa.JSON(), nullable=True),
    sa.Column('per_question_json', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_sessions_user_id'), 'mock_sessions', ['user_id'], unique=False)
    op.create_table('placement_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('college_name', sa.String(length=200), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.String(length=10), nullable=True),
    sa.Column('target_role', sa.String(length=120), nullable=True),
    sa.Column('target_companies', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('resume_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('jd_text', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('resume_json', sa.JSON(), nullable=True),
    sa.Column('template', sa.String(length=30), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_documents_user_id'), 'resume_documents', ['user_id'], unique=False)
    op.create_table('skill_radar_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_category', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_category', name='uq_user_skill')
    )
    op.create_index(op.f('ix_skill_radar_scores_user_id'), 'skill_radar_scores', ['user_id'], unique=False)
    op.create_table('tutor_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('source_page', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_history_user_id'), 'tutor_history', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=False),
    sa.Column('plan_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('roadmap_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_admin_id'), 'audit_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('posted_by', sa.String(length=36), nullable=False),
    sa.Column('college_id', sa.String(length=36), nullable=True),
    sa.Column('visibility', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('work_mode', sa.String(length=20), nullable=True),
    sa.Column('ctc_band', sa.String(length=60), nullable=True),
    sa.Column('stipend', sa.String(length=60), nullable=True),
    sa.Column('required_skills_json', sa.JSON(), nullable=True),
    sa.Column('eligibility_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('apply_url', sa.String(length=500), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_college_id'), 'job_postings', ['college_id'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_by'), 'job_postings', ['posted_by'], unique=False)
    op.create_table('roadmap_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=False),
    sa.Column('phase_id', sa.String(length=36), nullable=False),
    sa.Column('parent_topic_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('skill_category', sa.String(length=80), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['roadmap_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['domain_phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_topics_domain_id'), 'roadmap_topics', ['domain_id'], unique=False)
    op.create_index(op.f('ix_roadmap_topics_parent_topic_id'), 'roadmap_topics', ['parent_topic_id'], unique=False)
    op.create_index(op.f('ix_roadmap_topics_phase_id'), 'roadmap_topics', ['phase_id'], unique=False)
    op.create_index(op.f('ix_roadmap_topics_slug'), 'roadmap_topics', ['slug'], unique=False)
    op.create_table('job_tracking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job')
    )
    op.create_index(op.f('ix_job_tracking_job_id'), 'job_tracking', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_tracking_user_id'), 'job_tracking', ['user_id'], unique=False)
    op.create_table('topic_content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('concept_markdown', sa.Text(), nullable=True),
    sa.Column('examples_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['roadmap_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_content_topic_id'), 'topic_content', ['topic_id'], unique=True)
    op.create_table('topic_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_kind', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=12), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('why_explanation', sa.Text(), nullable=True),
    sa.Column('how_explanation', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('common_mistakes', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['roadmap_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_questions_topic_id'), 'topic_questions', ['topic_id'], unique=False)
    op.create_table('user_topic_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('questions_completed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['roadmap_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic')
    )
    op.create_index(op.f('ix_user_topic_progress_topic_id'), 'user_topic_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_progress_user_id'), 'user_topic_progress', ['user_id'], unique=False)
    op.create_table('user_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('is_first_attempt', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['topic_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_attempts_question_id'), 'user_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_attempts_user_id'), 'user_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_attempts_user_id'), table_name='user_attempts')
    op.drop_index(op.f('ix_user_attempts_question_id'), table_name='user_attempts')
    op.drop_table('user_attempts')
    op.drop_index(op.f('ix_user_topic_progress_user_id'), table_name='user_topic_progress')
    op.drop_index(op.f('ix_user_topic_progress_topic_id'), table_name='user_topic_progress')
    op.drop_table('user_topic_progress')
    op.drop_index(op.f('ix_topic_questions_topic_id'), table_name='topic_questions')
    op.drop_table('topic_questions')
    op.drop_index(op.f('ix_topic_content_topic_id'), table_name='topic_content')
    op.drop_table('topic_content')
    op.drop_index(op.f('ix_job_tracking_user_id'), table_name='job_tracking')
    op.drop_index(op.f('ix_job_tracking_job_id'), table_name='job_tracking')
    op.drop_table('job_tracking')
    op.drop_index(op.f('ix_roadmap_topics_slug'), table_name='roadmap_topics')
    op.drop_index(op.f('ix_roadmap_topics_phase_id'), table_name='roadmap_topics')
    op.drop_index(op.f('ix_roadmap_topics_parent_topic_id'), table_name='roadmap_topics')
    op.drop_index(op.f('ix_roadmap_topics_domain_id'), table_name='roadmap_topics')
    op.drop_table('roadmap_topics')
    op.drop_index(op.f('ix_job_postings_posted_by'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_college_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_admin_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_tutor_history_user_id'), table_name='tutor_history')
    op.drop_table('tutor_history')
    op.drop_index(op.f('ix_skill_radar_scores_user_id'), table_name='skill_radar_scores')
    op.drop_table('skill_radar_scores')
    op.drop_index(op.f('ix_resume_documents_user_id'), table_name='resume_documents')
    op.drop_table('resume_documents')
    op.drop_table('placement_profiles')
    op.drop_index(op.f('ix_mock_sessions_user_id'), table_name='mock_sessions')
    op.drop_table('mock_sessions')
    op.drop_index(op.f('ix_leaderboard_user_id'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_college_id'), table_name='leaderboard')
    op.drop_table('leaderboard')
    op.drop_index(op.f('ix_interview_studio_sessions_user_id'), table_name='interview_studio_sessions')
    op.drop_table('interview_studio_sessions')
    op.drop_index(op.f('ix_domain_phases_domain_id'), table_name='domain_phases')
    op.drop_table('domain_phases')
    op.drop_index(op.f('ix_daily_activity_user_id'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_activity_date'), table_name='daily_activity')
    op.drop_table('daily_activity')
    op.drop_index(op.f('ix_championship_attempts_user_id'), table_name='championship_attempts')
    op.drop_index(op.f('ix_championship_attempts_championship_id'), table_name='championship_attempts')
    op.drop_table('championship_attempts')
    op.drop_index(op.f('ix_arena_submissions_user_id'), table_name='arena_submissions')
    op.drop_index(op.f('ix_arena_submissions_problem_id'), table_name='arena_submissions')
    op.drop_table('arena_submissions')
    op.drop_index(op.f('ix_aptitude_sessions_user_id'), table_name='aptitude_sessions')
    op.drop_table('aptitude_sessions')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_college_id'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_college_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_slug'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_domains_slug'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_company_intel_cache_company_slug'), table_name='company_intel_cache')
    op.drop_table('company_intel_cache')
    op.drop_index(op.f('ix_colleges_slug'), table_name='colleges')
    op.drop_table('colleges')
    op.drop_index(op.f('ix_championships_college_id'), table_name='championships')
    op.drop_table('championships')
    op.drop_index(op.f('ix_badges_code'), table_name='badges')
    op.drop_table('badges')
    op.drop_table('arena_problems')
    # ### end Alembic commands ###